Repository wonyangs/webserv, pull requests merged in 2024-01, with the labels that each got.

#17 [Feat] RequestParser 기본 버전 구현
  Makefile
  core/Connection.cpp
  core/Connection.hpp
  http/Request.cpp
  http/Request.hpp
  http/RequestParser.cpp
  http/RequestParser.hpp
  utils/Enum.hpp
Labels: 💻 feat

#19 [Feat] RequestParser 구조 변경
  core/Connection.cpp
  core/Connection.hpp
  http/Request.cpp
  http/Request.hpp
  http/RequestParser.cpp
  http/RequestParser.hpp
Labels: 🛠 refactor, 💻 feat

#22 [Feat] 요청 처리 중 서버블록 선택을 위한 구조 수정
  Makefile
  config/Server.cpp
  config/Server.hpp
  core/Connection.cpp
  core/Connection.hpp
  core/EventLoop.cpp
  core/EventLoop.hpp
  core/ServerManager.cpp
  core/ServerManager.hpp
  main.cpp
  utils/Config.cpp
  utils/Config.hpp
Labels: 💻 feat

#25 [Fix] 클라이언트가 연결을 종료했을 때 관리가 되지 않던 오류 수정
  core/Connection.cpp
  core/Connection.hpp
  core/ServerManager.cpp
Labels: 🐞 fix

#27 [Feat] Chunked Transfer Coding 구현
  http/RequestParser.cpp
  http/RequestParser.hpp
Labels: 🛠 refactor, 🐞 fix, 💻 feat

#26 [Refactor] 서버 구조 리팩토링
  Makefile
  core/ServerManager.cpp
  main.cpp
  server/Connection.cpp
  server/Connection.hpp
  server/EventLoop.cpp
  server/EventLoop.hpp
  server/ServerManager.cpp
  server/ServerManager.hpp
Labels: 🛠 refactor

#32 [Feat] request-target의 query 파싱
  http/Request.cpp
  http/Request.hpp
  utils/Config.hpp
Labels: 💻 feat

#34 [Feat] Response 클래스 구현
  Makefile
  http/Response.cpp
  http/Response.hpp
Labels: 💻 feat

#36 [Feat] Kqueue 모든 이벤트 제거 기능 추가
  core/Kqueue.cpp
  core/Kqueue.hpp
  server/ServerManager.cpp
Labels: 💻 feat

#38 [Feat] 기본 에러 페이지 구현
  server/Connection.cpp
  utils/Config.cpp
  utils/Config.hpp
Labels: 💻 feat

#41 [Feat] ServerManager에 fd 관리 컨테이너 추가
  server/ServerManager.cpp
  server/ServerManager.hpp
Labels: 💻 feat

#42 [feat] 서버 재시작 기능 구현
  server/EventLoop.cpp
  server/EventLoop.hpp
  server/ServerManager.cpp
  server/ServerManager.hpp
Labels: 💻 feat

#43 [Feat] AResponseBuilder 설계 및 ErrorBuilder 기본 에러 페이지 반환
  Makefile
  config/Location.cpp
  config/Location.hpp
  http/AResponseBuilder.cpp
  http/AResponseBuilder.hpp
  http/ErrorBuilder.cpp
  http/ErrorBuilder.hpp
  http/Request.cpp
  http/Request.hpp
  http/RequestParser.cpp
  http/RequestParser.hpp
  http/Response.cpp
  http/Response.hpp
  server/Connection.cpp
  server/Connection.hpp
  utils/Config.cpp
  utils/Config.hpp
  utils/Util.cpp
  utils/Util.hpp
Labels: 🛠 refactor, 💻 feat

#45 [Feat] 전체적인 응답 생성 및 전송 흐름 설계 구현
  Makefile
  core/Kqueue.cpp
  http/AResponseBuilder.cpp
  http/AResponseBuilder.hpp
  http/ErrorBuilder.cpp
  http/ErrorBuilder.hpp
  http/Request.cpp
  http/Request.hpp
  server/Connection.cpp
  server/Connection.hpp
  server/ServerManager.cpp
  server/ServerManager.hpp
Labels: 🐞 fix, 💻 feat

#47 [Feat] 버퍼 사이즈만큼 HTTP 응답 전송
  http/AResponseBuilder.cpp
  http/AResponseBuilder.hpp
  http/Response.cpp
  http/Response.hpp
  server/Connection.cpp
  server/Connection.hpp
  server/ServerManager.cpp
Labels: 💻 feat

#49 [Feat] error_page가 적용된 Error response 구현
  http/AResponseBuilder.hpp
  http/ErrorBuilder.cpp
  http/ErrorBuilder.hpp
  server/Connection.cpp
  server/Connection.hpp
  server/ServerManager.cpp
  www/404.html
Labels: 💻 feat

#51 [Feat] AutoindexBuilder 구현
  Makefile
  http/AResponseBuilder.hpp
  http/AutoindexBuilder.cpp
  http/AutoindexBuilder.hpp
  server/Connection.cpp
  server/Connection.hpp
Labels: 💻 feat

#52 [Feat] StaticFileBuilder 구현
  Makefile
  config/Location.cpp
  http/AResponseBuilder.hpp
  http/StaticFileBuilder.cpp
  http/StaticFileBuilder.hpp
  main.cpp
  server/Connection.cpp
  server/Connection.hpp
  utils/Config.cpp
  utils/Config.hpp
  www/cat.html
  www/images/ancco.png
Labels: 💻 feat

#58 [Feat] RedirectBuilder 구현
  Makefile
  http/AResponseBuilder.hpp
  http/RedirectBuilder.cpp
  http/RedirectBuilder.hpp
  server/Connection.cpp
  server/Connection.hpp
Labels: 💻 feat

#60 [Feat] CGI builder 제작을 위한 사전 작업
  config/Location.cpp
  config/Location.hpp
  core/Event.cpp
  core/Event.hpp
  core/Kqueue.cpp
  core/Kqueue.hpp
  http/AResponseBuilder.hpp
  http/AutoindexBuilder.cpp
  http/AutoindexBuilder.hpp
  http/ErrorBuilder.cpp
  http/ErrorBuilder.hpp
  http/RedirectBuilder.cpp
  http/RedirectBuilder.hpp
  http/StaticFileBuilder.cpp
  http/StaticFileBuilder.hpp
  server/Connection.cpp
  server/Connection.hpp
  server/ServerManager.cpp
  server/ServerManager.hpp
Labels: 💻 feat

#61 [Feat] response builder 선택
  http/AResponseBuilder.cpp
  http/AResponseBuilder.hpp
  http/AutoindexBuilder.cpp
  http/ErrorBuilder.cpp
  http/ErrorBuilder.hpp
  http/RedirectBuilder.cpp
  http/Request.cpp
  http/Request.hpp
  http/RequestParser.cpp
  http/RequestParser.hpp
  http/StaticFileBuilder.cpp
  server/Connection.cpp
  server/Connection.hpp
  server/ServerManager.cpp
  utils/Config.cpp
  utils/Config.hpp
  www/images/bird.png
  www/images/index_bear.png
Labels: 🛠 refactor, 🐞 fix, 💻 feat

#63 [Feat] request 값 유효성 검사
  http/AutoindexBuilder.cpp
  http/ErrorBuilder.cpp
  http/ErrorBuilder.hpp
  http/Request.cpp
  http/Request.hpp
  http/RequestParser.cpp
  http/RequestParser.hpp
  http/StaticFileBuilder.cpp
  http/StaticFileBuilder.hpp
  server/Connection.cpp
  server/Connection.hpp
  utils/Config.cpp
  utils/Config.hpp
Labels: 🛠 refactor, 🐞 fix, 💻 feat

#67 [Feat] builder select 로직 수정 및 BuilderSelector 클래스 구현
  Makefile
  config/Server.hpp
  http/AutoindexBuilder.hpp
  http/BuilderSelector.cpp
  http/BuilderSelector.hpp
  http/CgiBuilder.cpp
  http/CgiBuilder.hpp
  http/ErrorBuilder.hpp
  http/Request.cpp
  http/Request.hpp
  http/RequestParser.hpp
  http/Response.hpp
  http/StaticFileBuilder.hpp
  main.cpp
  server/Connection.cpp
  server/Connection.hpp
  server/EventLoop.hpp
  server/ServerManager.cpp
  utils/Config.hpp
  utils/Util.hpp
Labels: 🐞 fix, 💻 feat, 🔸 chore

#70 [Feat] 파일 업로드 및 삭제 구현
  Makefile
  cgi-bin/hello.py
  cgi-bin/image-view.py
  cgi-bin/my-python-cgi.py
  cgi-bin/query.py
  cgi-bin/test.py
  cgi-bin/upload.py
  http/AResponseBuilder.hpp
  http/BuilderSelector.cpp
  http/BuilderSelector.hpp
  http/CgiBuilder.cpp
  http/CgiBuilder.hpp
  http/DeleteBuilder.cpp
  http/DeleteBuilder.hpp
  http/Request.cpp
  main.cpp
  www/upload.html
  www/upload/ancco.png
  www/upload/bird.png
  www/upload/dog.png
  www/upload/index_bear.png
Labels: 🐞 fix, 💻 feat

#72 [Feat] 상대경로를 제거하여 반환하는 함수 구현
  utils/Util.cpp
  utils/Util.hpp
Labels: 💻 feat

#74 [Feat] Ruby CGI 추가 및 쿠키세션 예제 구현
  cgi-bin/hello.rb
  cgi-bin/image-view.py
  cgi-bin/login.py
  cgi-bin/logout.py
  cgi-bin/my-ruby-cgi.rb
  cgi-bin/session-status.py
  main.cpp
  www/login.html
  www/upload.html
Labels: 💻 feat

#75 [Feat] config 설정파일 파싱
  Makefile
  conf/default.conf
  conf/tester.conf
  config/ConfigParser.cpp
  config/ConfigParser.hpp
  config/Location.cpp
  config/Location.hpp
  config/Server.cpp
  config/Server.hpp
  http/BuilderSelector.hpp
  http/Request.cpp
  http/Request.hpp
  http/RequestParser.cpp
  http/RequestParser.hpp
  main.cpp
  utils/Util.cpp
  utils/Util.hpp
Labels: 🛠 refactor, 💻 feat, 🔸 chore

#77 [Feat] config 값 유효성 검사
  conf/default.conf
  conf/tester.conf
  config/ConfigParser.cpp
  config/ConfigParser.hpp
  config/Location.cpp
  config/Location.hpp
  config/Server.cpp
  config/Server.hpp
  core/Socket.hpp
  http/BuilderSelector.cpp
  http/CgiBuilder.cpp
  http/CgiBuilder.hpp
  http/ErrorBuilder.cpp
  http/Request.cpp
  http/RequestParser.cpp
  http/Response.cpp
  http/StaticFileBuilder.cpp
  server/Connection.cpp
  utils/Util.cpp
  utils/Util.hpp
Labels: 🛠 refactor, 🐞 fix, 💻 feat, 🔸 chore
